name: Build Harvester

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_OWN: futuretea
  REPO_NAME: harvester-installer
  REPO_BRANCH: futuretea
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Prune docker, please wait ..."
        docker system prune --volumes -a -f

        echo "Prune system, please wait ..."
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php* >/dev/null 2>&1
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php >/dev/null 2>&1
        sudo -E apt-get -y autoremove --purge >/dev/null 2>&1
        sudo -E apt-get clean >/dev/null 2>&1
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone https://github.com/${REPO_OWN}/${REPO_NAME} -b $REPO_BRANCH ${REPO_NAME}
        ln -sf /workdir/${REPO_NAME} ${GITHUB_WORKSPACE}/${REPO_NAME}


    - name: Run make
      id: make
      run: |
        cd $GITHUB_WORKSPACE/${REPO_NAME}
        make

    - name: Generate release tag
      id: tag
      run: |
        pushd $GITHUB_WORKSPACE/${REPO_NAME}
        source scripts/version
        popd

        echo "Base on ${REPO_OWN}/${REPO_NAME}@${COMMIT}" > release.txt
        echo "::set-output name=artifacts::${GITHUB_WORKSPACE}/${REPO_NAME}/dist/artifacts"
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")-${VERSION}"
        echo "::set-output name=status::success"

    - name: Upload iso to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ steps.tag.outputs.artifacts }}/*

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        keep_latest: 3
        delete_tags: true

