name: Build Harvester

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Test gdrive-upload-action
      id: gdrive
      uses: futuretea/gdrive-upload-action@test
      with:
        filename: README.md
        target: test-file.md
        folderId:  ${{ secrets.GDRIVE_FOLDER_ID }}
        credentials: ${{ secrets.GDRIVE_CREDENTIALS }}

    - name: Generate release info
      env:
        GDRIVE_DOWNLOAD_URL: ${{ steps.gdrive.outputs.downloadURL }}
      run: |
        echo "🧊 [Offline ISO](${GDRIVE_DOWNLOAD_URL})"

